# Generated by Django 4.0.5 on 2022-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
