# Generated by Django 4.0.5 on 2022-07-16 12:55

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_aboutus_image_aboutus_image1_aboutus_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
            ],
        ),
    ]
