# Generated by Django 4.1 on 2022-08-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('decription', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('team_leader_name', models.CharField(max_length=200)),
                ('team_leader_message', models.TextField()),
                ('team_leader_image', models.ImageField(upload_to='')),
                ('gallery', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
    ]
