# Generated by Django 4.1 on 2022-08-25 06:53

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministries',
            name='latest_yt',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
