# Generated by Django 4.1 on 2022-08-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_ministries_latest_yt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioSermon',
            new_name='Podcast',
        ),
    ]
