# Generated by Django 4.1 on 2022-09-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_rename_audiosermon_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.IntegerField()),
                ('reasons_for_giving', models.CharField(choices=[('GTN', 'GRACE TO NATION'), ('VOICE OF MY SPIRIT', 'VOICE OF MY SPIRIT'), ('PRAISE', 'PRAISE'), ('CHURCH SERVICE', 'CHURCH SERVICE'), ('CHILDREN MINISTRY', 'CHILDREN MINISTRY')], max_length=200)),
                ('give_in_currency', models.CharField(choices=[('USD', 'USD'), ('KES', 'KES'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD')], max_length=20)),
            ],
        ),
    ]
