# Generated by Django 4.1.3 on 2022-11-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_giving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='audio',
        ),
        migrations.AddField(
            model_name='giving',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
