# Generated by Django 4.1.3 on 2022-11-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_podcast_audio_giving_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUS',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='VideoClips',
        ),
        migrations.RemoveField(
            model_name='ministries',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='ministries',
            name='latest_yt',
        ),
        migrations.RemoveField(
            model_name='ministries',
            name='team_leader_image',
        ),
        migrations.RemoveField(
            model_name='ministries',
            name='team_leader_message',
        ),
        migrations.RemoveField(
            model_name='ministries',
            name='team_leader_name',
        ),
        migrations.RemoveField(
            model_name='sermons',
            name='static_video',
        ),
    ]
