# Generated by Django 4.0.5 on 2022-07-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
